// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdw8z0ouJ9sbgWT2kYslueb_dILiX8hnU',
    appId: '1:123011165933:web:c6671b2c0490ad262aa6e4',
    messagingSenderId: '123011165933',
    projectId: 'testing-wsi',
    authDomain: 'testing-wsi.firebaseapp.com',
    storageBucket: 'testing-wsi.firebasestorage.app',
    measurementId: 'G-S6J0TN3NHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD20boV-VD861aPsodb7fUbjxDNznlL31c',
    appId: '1:123011165933:android:478c71a5c7d087752aa6e4',
    messagingSenderId: '123011165933',
    projectId: 'testing-wsi',
    storageBucket: 'testing-wsi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArmHCOPLcgp2tigzpQfa6gEOqGytgpGCA',
    appId: '1:123011165933:ios:0b4fd0e7156dc0672aa6e4',
    messagingSenderId: '123011165933',
    projectId: 'testing-wsi',
    storageBucket: 'testing-wsi.firebasestorage.app',
    iosBundleId: 'com.example.concept2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArmHCOPLcgp2tigzpQfa6gEOqGytgpGCA',
    appId: '1:123011165933:ios:0b4fd0e7156dc0672aa6e4',
    messagingSenderId: '123011165933',
    projectId: 'testing-wsi',
    storageBucket: 'testing-wsi.firebasestorage.app',
    iosBundleId: 'com.example.concept2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdw8z0ouJ9sbgWT2kYslueb_dILiX8hnU',
    appId: '1:123011165933:web:c01a6b26f90ba9a32aa6e4',
    messagingSenderId: '123011165933',
    projectId: 'testing-wsi',
    authDomain: 'testing-wsi.firebaseapp.com',
    storageBucket: 'testing-wsi.firebasestorage.app',
    measurementId: 'G-RBHSR1CGZ9',
  );

}